"""Pre-defined puzzle bank for Strayz game."""

PUZZLE_BANK = [
    # ---------------- LEVEL 1: JUNGLE RUINS (Math & Logic) ----------------
    {
        "level": 1,
        "type": "trivia",
        "category": "math",
        "question": "An ancient Mayan tablet shows: 7, 14, 28, 56, ?  What is the next number?",
        "options": ["72", "98", "112", "120"],
        "answer": "112",
        "hint": "Each number is double the previous one.",
        "explanation": "The pattern doubles each time: 56 x 2 = 112.",
    },
    {
        "level": 1,
        "type": "riddle",
        "category": "logic",
        "question": "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
        "options": ["A painting", "A map", "A book", "A dream"],
        "answer": "A map",
        "hint": "Adventurers use me to find treasure.",
        "explanation": "A map shows places without containing them physically.",
    },
    {
        "level": 1,
        "type": "trivia",
        "category": "math",
        "question": "The temple door requires the answer: If a vine grows 3 cm each day and is now 21 cm long, how many days has it been growing?",
        "options": ["5", "6", "7", "8"],
        "answer": "7",
        "hint": "Divide the total by the daily growth.",
        "explanation": "21 ÷ 3 = 7 days.",
    },
    {
        "level": 1,
        "type": "trivia",
        "category": "logic",
        "question": "Three explorers each carry 2 torches. They meet 4 more explorers carrying 1 torch each. How many torches in total?",
        "options": ["7", "10", "12", "9"],
        "answer": "10",
        "hint": "Count both groups: 3x2 and 4x1.",
        "explanation": "(3×2) + (4×1) = 6 + 4 = 10 torches.",
    },

    # ---------------- LEVEL 2: MUSICAL MUSEUM (Music Trivia) ----------------
    {
        "level": 2,
        "type": "trivia",
        "category": "music",
        "question": "Which composer wrote 'The Four Seasons'?",
        "options": ["Mozart", "Vivaldi", "Beethoven", "Bach"],
        "answer": "Vivaldi",
        "hint": "He was an Italian Baroque composer.",
        "explanation": "Antonio Vivaldi composed 'The Four Seasons' around 1720.",
    },
    {
        "level": 2,
        "type": "trivia",
        "category": "music",
        "question": "How many strings does a standard violin have?",
        "options": ["3", "4", "5", "6"],
        "answer": "4",
        "hint": "Less than a guitar.",
        "explanation": "A violin has 4 strings: G, D, A, E.",
    },
    {
        "level": 2,
        "type": "riddle",
        "category": "music",
        "question": "I can be sharp or flat, but I'm never sick. I sit on a line or in a space. What am I?",
        "options": ["A note", "A pencil", "A bird", "A leaf"],
        "answer": "A note",
        "hint": "You can read me on a staff.",
        "explanation": "A musical note can be sharp or flat and sits on staff lines.",
    },
    {
        "level": 2,
        "type": "trivia",
        "category": "music",
        "question": "Which instrument family does the saxophone belong to?",
        "options": ["Brass", "String", "Woodwind", "Percussion"],
        "answer": "Woodwind",
        "hint": "Despite being made of metal, it uses a reed.",
        "explanation": "The saxophone is a woodwind because it produces sound with a reed.",
    },

    # ---------------- LEVEL 3: ANCIENT LIBRARY (History & Geography) ----------------
    {
        "level": 3,
        "type": "trivia",
        "category": "geography",
        "question": "What is the capital of Australia?",
        "options": ["Sydney", "Melbourne", "Canberra", "Perth"],
        "answer": "Canberra",
        "hint": "It's not the biggest city.",
        "explanation": "Canberra is Australia's purpose-built capital city.",
    },
    {
        "level": 3,
        "type": "trivia",
        "category": "history",
        "question": "In which year did humans first land on the Moon?",
        "options": ["1965", "1969", "1972", "1959"],
        "answer": "1969",
        "hint": "Apollo 11 mission, late 60s.",
        "explanation": "Neil Armstrong stepped onto the Moon on July 20, 1969.",
    },
    {
        "level": 3,
        "type": "riddle",
        "category": "geography",
        "question": "The more you take, the more you leave behind. What am I?",
        "options": ["Memories", "Footsteps", "Photos", "Time"],
        "answer": "Footsteps",
        "hint": "Adventurers leave them in the sand.",
        "explanation": "The more steps you take, the more footprints you leave behind.",
    },
    {
        "level": 3,
        "type": "trivia",
        "category": "geography",
        "question": "Which is the longest river in the world?",
        "options": ["Amazon", "Nile", "Yangtze", "Mississippi"],
        "answer": "Nile",
        "hint": "It flows through Egypt.",
        "explanation": "The Nile is approximately 6,650 km long.",
    },

    # ---------------- LEVEL 4: SCIENCE LAB (Science & Nature) ----------------
    {
        "level": 4,
        "type": "trivia",
        "category": "science",
        "question": "What is the chemical symbol for Gold?",
        "options": ["Go", "Gd", "Au", "Ag"],
        "answer": "Au",
        "hint": "From its Latin name 'aurum'.",
        "explanation": "Au comes from the Latin word 'aurum' meaning gold.",
    },
    {
        "level": 4,
        "type": "trivia",
        "category": "science",
        "question": "Which planet has the most moons?",
        "options": ["Jupiter", "Saturn", "Uranus", "Neptune"],
        "answer": "Saturn",
        "hint": "Famous for its rings.",
        "explanation": "Saturn has over 140 confirmed moons, more than any other planet.",
    },
    {
        "level": 4,
        "type": "riddle",
        "category": "nature",
        "question": "I'm tall when I'm young, and short when I'm old. What am I?",
        "options": ["A tree", "A candle", "A shadow", "A mountain"],
        "answer": "A candle",
        "hint": "I burn down over time.",
        "explanation": "A candle starts tall and shrinks as it burns.",
    },
    {
        "level": 4,
        "type": "trivia",
        "category": "science",
        "question": "How many bones are in an adult human body?",
        "options": ["186", "206", "226", "246"],
        "answer": "206",
        "hint": "Babies have more (around 270).",
        "explanation": "Adults have 206 bones; many fuse together as we grow.",
    },

    # ---------------- LEVEL 5: FINAL SHOWDOWN (Mixed) ----------------
    {
        "level": 5,
        "type": "trivia",
        "category": "history",
        "question": "Who painted the Mona Lisa?",
        "options": ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"],
        "answer": "Leonardo da Vinci",
        "hint": "Also designed flying machines.",
        "explanation": "Leonardo da Vinci painted the Mona Lisa between 1503-1519.",
    },
    {
        "level": 5,
        "type": "trivia",
        "category": "math",
        "question": "What is 15% of 200?",
        "options": ["25", "30", "35", "40"],
        "answer": "30",
        "hint": "10% is 20, half of that is 10.",
        "explanation": "15% of 200 = 0.15 × 200 = 30.",
    },
    {
        "level": 5,
        "type": "riddle",
        "category": "logic",
        "question": "What has hands but cannot clap?",
        "options": ["A statue", "A clock", "A doll", "A glove"],
        "answer": "A clock",
        "hint": "I tell you the time.",
        "explanation": "A clock has hour and minute hands but cannot clap them.",
    },
    {
        "level": 5,
        "type": "trivia",
        "category": "music",
        "question": "Which Beatles song features the lyric 'Let it be'?",
        "options": ["Hey Jude", "Yesterday", "Let It Be", "Help!"],
        "answer": "Let It Be",
        "hint": "The title says it all.",
        "explanation": "'Let It Be' was released in 1970 as the title track.",
    },
    {
        "level": 5,
        "type": "trivia",
        "category": "science",
        "question": "What gas do plants absorb from the air for photosynthesis?",
        "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
        "answer": "Carbon Dioxide",
        "hint": "Humans exhale it.",
        "explanation": "Plants absorb CO2 and release oxygen during photosynthesis.",
    },
]


PATTERN_PUZZLES = [
    {
        "level": 1,
        "type": "pattern",
        "category": "logic",
        "question": "Memorize the sequence then repeat it: Red, Blue, Yellow, Green",
        "sequence": ["red", "blue", "yellow", "green"],
        "hint": "Try to remember the order.",
        "explanation": "Pattern recognition trains your working memory.",
    },
    {
        "level": 2,
        "type": "pattern",
        "category": "music",
        "question": "Memorize this melody sequence",
        "sequence": ["do", "mi", "sol", "do", "fa"],
        "hint": "Sing it in your head.",
        "explanation": "Musical sequences strengthen tonal memory.",
    },
    {
        "level": 3,
        "type": "pattern",
        "category": "logic",
        "question": "Remember this ancient symbol sequence",
        "sequence": ["red", "yellow", "blue", "green", "red", "yellow"],
        "hint": "Look for repeating patterns.",
        "explanation": "Recognizing repetition is key to pattern solving.",
    },
    {
        "level": 4,
        "type": "pattern",
        "category": "science",
        "question": "Memorize the lab element colors",
        "sequence": ["blue", "green", "red", "yellow", "blue", "green", "red"],
        "hint": "It's a 4-color cycle.",
        "explanation": "Recurring sequences appear throughout chemistry.",
    },
    {
        "level": 5,
        "type": "pattern",
        "category": "logic",
        "question": "The final sequence — memorize carefully!",
        "sequence": ["red", "blue", "green", "yellow", "red", "green", "blue", "yellow"],
        "hint": "Stay focused.",
        "explanation": "Long sequences test your memory limits.",
    },
]
