"""Pre-defined puzzle bank for Strayz game."""

PUZZLE_BANK = [
    # ---------------- LEVEL 1: JUNGLE RUINS (Math & Logic primary) ----------------
    {
        "level": 1,
        "type": "trivia",
        "category": "math",
        "question": "If a stone wheel has 12 spokes and 1/3 are broken, how many remain intact?",
        "options": ["6", "7", "8", "9"],
        "answer": "8",
        "hint": "12 ÷ 3 = 4 broken.",
        "explanation": "12 − 4 = 8 spokes remain intact.",
    },
    {
        "level": 1,
        "type": "trivia",
        "category": "logic",
        "question": "If all jungles have trees and this place has no trees, what is it NOT?",
        "options": ["A desert", "A jungle", "A lake", "A city"],
        "answer": "A jungle",
        "hint": "Use the rule: jungles always have trees.",
        "explanation": "By the contrapositive: no trees → not a jungle.",
    },
    {
        "level": 1,
        "type": "trivia",
        "category": "math",
        "question": "An ancient Mayan tablet shows: 7, 14, 28, 56, ?  What is the next number?",
        "options": ["72", "98", "112", "120"],
        "answer": "112",
        "hint": "Each number is double the previous one.",
        "explanation": "The pattern doubles each time: 56 x 2 = 112.",
    },
    {
        "level": 1,
        "type": "riddle",
        "category": "logic",
        "question": "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?",
        "options": ["A painting", "A map", "A book", "A dream"],
        "answer": "A map",
        "hint": "Adventurers use me to find treasure.",
        "explanation": "A map shows places without containing them physically.",
    },
    {
        "level": 1,
        "type": "trivia",
        "category": "nature",
        "question": "Which jungle animal is famous for being the largest of the big cats in the Americas?",
        "options": ["Cougar", "Ocelot", "Jaguar", "Panther"],
        "answer": "Jaguar",
        "hint": "Its name starts with J and it has rosette spots.",
        "explanation": "The jaguar is the largest cat in the Americas and a symbol in Mayan culture.",
    },
    {
        "level": 1,
        "type": "trivia",
        "category": "math",
        "question": "The temple door requires the answer: If a vine grows 3 cm each day and is now 21 cm long, how many days has it been growing?",
        "options": ["5", "6", "7", "8"],
        "answer": "7",
        "hint": "Divide the total by the daily growth.",
        "explanation": "21 ÷ 3 = 7 days.",
    },
    {
        "level": 1,
        "type": "trivia",
        "category": "history",
        "question": "Which ancient civilisation built the iconic Mayan pyramids?",
        "options": ["The Aztecs", "The Maya", "The Incas", "The Olmecs"],
        "answer": "The Maya",
        "hint": "Hint: it's literally in the pyramid's name.",
        "explanation": "The Maya civilisation thrived in Mesoamerica from ~2000 BCE to 1500 CE.",
    },

    # ---------------- LEVEL 2: MUSICAL MUSEUM (Music primary) ----------------
    {
        "level": 2,
        "type": "trivia",
        "category": "music",
        "question": "Which composer wrote 'The Four Seasons'?",
        "options": ["Mozart", "Vivaldi", "Beethoven", "Bach"],
        "answer": "Vivaldi",
        "hint": "He was an Italian Baroque composer.",
        "explanation": "Antonio Vivaldi composed 'The Four Seasons' around 1720.",
    },
    {
        "level": 2,
        "type": "trivia",
        "category": "math",
        "question": "If a song has 120 beats per minute, how many beats are in 30 seconds?",
        "options": ["30", "60", "90", "120"],
        "answer": "60",
        "hint": "30 seconds is half a minute.",
        "explanation": "120 BPM ÷ 2 = 60 beats in 30 seconds.",
    },
    {
        "level": 2,
        "type": "trivia",
        "category": "music",
        "question": "How many strings does a standard violin have?",
        "options": ["3", "4", "5", "6"],
        "answer": "4",
        "hint": "Less than a guitar.",
        "explanation": "A violin has 4 strings: G, D, A, E.",
    },
    {
        "level": 2,
        "type": "riddle",
        "category": "logic",
        "question": "I can be sharp or flat, but I'm never sick. I sit on a line or in a space. What am I?",
        "options": ["A note", "A pencil", "A bird", "A leaf"],
        "answer": "A note",
        "hint": "You can read me on a staff.",
        "explanation": "A musical note can be sharp or flat and sits on staff lines.",
    },
    {
        "level": 2,
        "type": "trivia",
        "category": "geography",
        "question": "Which country gave us the famous opera composer Giuseppe Verdi?",
        "options": ["Germany", "Austria", "Italy", "France"],
        "answer": "Italy",
        "hint": "Land of pasta and pizza.",
        "explanation": "Verdi (1813-1901) was an Italian composer renowned for opera.",
    },

    # ---------------- LEVEL 3: ANCIENT LIBRARY (History & Geography primary) ----------------
    {
        "level": 3,
        "type": "trivia",
        "category": "geography",
        "question": "What is the capital of Australia?",
        "options": ["Sydney", "Melbourne", "Canberra", "Perth"],
        "answer": "Canberra",
        "hint": "It's not the biggest city.",
        "explanation": "Canberra is Australia's purpose-built capital city.",
    },
    {
        "level": 3,
        "type": "trivia",
        "category": "music",
        "question": "Which classical instrument did Wolfgang Amadeus Mozart first master as a child prodigy?",
        "options": ["Harp", "Piano (then 'harpsichord')", "Violin only", "Cello"],
        "answer": "Piano (then 'harpsichord')",
        "hint": "It has black and white keys today.",
        "explanation": "Mozart famously played the keyboard (harpsichord/piano) from age 3.",
    },
    {
        "level": 3,
        "type": "trivia",
        "category": "history",
        "question": "In which year did humans first land on the Moon?",
        "options": ["1965", "1969", "1972", "1959"],
        "answer": "1969",
        "hint": "Apollo 11 mission, late 60s.",
        "explanation": "Neil Armstrong stepped onto the Moon on July 20, 1969.",
    },
    {
        "level": 3,
        "type": "riddle",
        "category": "logic",
        "question": "The more you take, the more you leave behind. What am I?",
        "options": ["Memories", "Footsteps", "Photos", "Time"],
        "answer": "Footsteps",
        "hint": "Adventurers leave them in the sand.",
        "explanation": "The more steps you take, the more footprints you leave behind.",
    },
    {
        "level": 3,
        "type": "trivia",
        "category": "math",
        "question": "An ancient scroll lists: II, IV, VIII, XVI, ?  What's next in Roman numerals?",
        "options": ["XX", "XXIV", "XXX", "XXXII"],
        "answer": "XXXII",
        "hint": "Each is double the previous (Arabic: 2,4,8,16,?).",
        "explanation": "2,4,8,16,32 — and 32 in Roman is XXXII.",
    },

    # ---------------- LEVEL 4: SCIENCE LAB (Science & Nature primary) ----------------
    {
        "level": 4,
        "type": "trivia",
        "category": "science",
        "question": "What is the chemical symbol for Gold?",
        "options": ["Go", "Gd", "Au", "Ag"],
        "answer": "Au",
        "hint": "From its Latin name 'aurum'.",
        "explanation": "Au comes from the Latin word 'aurum' meaning gold.",
    },
    {
        "level": 4,
        "type": "trivia",
        "category": "history",
        "question": "Which scientist famously stated 'E = mc²'?",
        "options": ["Isaac Newton", "Albert Einstein", "Marie Curie", "Galileo Galilei"],
        "answer": "Albert Einstein",
        "hint": "Bushy hair, theory of relativity.",
        "explanation": "Einstein published his mass-energy equivalence in 1905.",
    },
    {
        "level": 4,
        "type": "trivia",
        "category": "science",
        "question": "Which planet has the most moons?",
        "options": ["Jupiter", "Saturn", "Uranus", "Neptune"],
        "answer": "Saturn",
        "hint": "Famous for its rings.",
        "explanation": "Saturn has over 140 confirmed moons, more than any other planet.",
    },
    {
        "level": 4,
        "type": "riddle",
        "category": "nature",
        "question": "I'm tall when I'm young, and short when I'm old. What am I?",
        "options": ["A tree", "A candle", "A shadow", "A mountain"],
        "answer": "A candle",
        "hint": "I burn down over time.",
        "explanation": "A candle starts tall and shrinks as it burns.",
    },
    {
        "level": 4,
        "type": "trivia",
        "category": "music",
        "question": "Sound waves travel fastest through which medium?",
        "options": ["Air (gas)", "Water (liquid)", "Steel (solid)", "A vacuum"],
        "answer": "Steel (solid)",
        "hint": "Tightly packed molecules transmit vibrations quicker.",
        "explanation": "Sound travels ~17x faster through steel than through air.",
    },

    # ---------------- LEVEL 5: FINAL SHOWDOWN (Mixed Mastery) ----------------
    {
        "level": 5,
        "type": "trivia",
        "category": "history",
        "question": "Who painted the Mona Lisa?",
        "options": ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"],
        "answer": "Leonardo da Vinci",
        "hint": "Also designed flying machines.",
        "explanation": "Leonardo da Vinci painted the Mona Lisa between 1503-1519.",
    },
    {
        "level": 5,
        "type": "trivia",
        "category": "math",
        "question": "What is 15% of 200?",
        "options": ["25", "30", "35", "40"],
        "answer": "30",
        "hint": "10% is 20, half of that is 10.",
        "explanation": "15% of 200 = 0.15 × 200 = 30.",
    },
    {
        "level": 5,
        "type": "riddle",
        "category": "logic",
        "question": "What has hands but cannot clap?",
        "options": ["A statue", "A clock", "A doll", "A glove"],
        "answer": "A clock",
        "hint": "I tell you the time.",
        "explanation": "A clock has hour and minute hands but cannot clap them.",
    },
    {
        "level": 5,
        "type": "trivia",
        "category": "music",
        "question": "Which Beatles song features the lyric 'Let it be'?",
        "options": ["Hey Jude", "Yesterday", "Let It Be", "Help!"],
        "answer": "Let It Be",
        "hint": "The title says it all.",
        "explanation": "'Let It Be' was released in 1970 as the title track.",
    },
    {
        "level": 5,
        "type": "trivia",
        "category": "science",
        "question": "What gas do plants absorb from the air for photosynthesis?",
        "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
        "answer": "Carbon Dioxide",
        "hint": "Humans exhale it.",
        "explanation": "Plants absorb CO2 and release oxygen during photosynthesis.",
    },

    # ---------------- LEVEL 6: SPORTS ARENA (Sports & Endurance) ----------------
    {
        "level": 6,
        "type": "trivia",
        "category": "sports",
        "question": "How long is a standard soccer (football) match without extra time?",
        "options": ["80 min", "90 min", "100 min", "120 min"],
        "answer": "90 min",
        "hint": "Two 45-minute halves.",
        "explanation": "A standard match is 90 minutes plus stoppage time.",
    },
    {
        "level": 6,
        "type": "trivia",
        "category": "sports",
        "question": "In a standard golf game, what is a 'birdie'?",
        "options": ["One under par", "Equal to par", "One over par", "Two under par"],
        "answer": "One under par",
        "hint": "Eagle is two under, albatross three under.",
        "explanation": "A birdie is finishing a hole at one stroke under par.",
    },
    {
        "level": 6,
        "type": "trivia",
        "category": "sports",
        "question": "Which country has won the most FIFA World Cup tournaments?",
        "options": ["Germany", "Italy", "Brazil", "Argentina"],
        "answer": "Brazil",
        "hint": "Famous for their yellow-and-green shirts.",
        "explanation": "Brazil has won the FIFA World Cup five times (1958, 1962, 1970, 1994, 2002).",
    },
    {
        "level": 6,
        "type": "trivia",
        "category": "sports",
        "question": "How many rings are on the Olympic flag?",
        "options": ["4", "5", "6", "7"],
        "answer": "5",
        "hint": "One for each major continent.",
        "explanation": "The five rings symbolise the union of the five inhabited continents.",
    },
    {
        "level": 6,
        "type": "trivia",
        "category": "math",
        "question": "A marathon is 42.195 km long. Roughly how many miles is that?",
        "options": ["20 miles", "26 miles", "30 miles", "42 miles"],
        "answer": "26 miles",
        "hint": "1 mile is about 1.6 km.",
        "explanation": "42.195 km ≈ 26.22 miles — the official marathon distance.",
    },
    {
        "level": 6,
        "type": "trivia",
        "category": "sports",
        "question": "Which sport was invented in Springfield, Massachusetts in 1891?",
        "options": ["Basketball", "Volleyball", "Baseball", "American Football"],
        "answer": "Basketball",
        "hint": "Dr. James Naismith invented it.",
        "explanation": "James Naismith created basketball in 1891 using peach baskets and a soccer ball.",
    },
    {
        "level": 6,
        "type": "riddle",
        "category": "logic",
        "question": "I have a face but no eyes, hands but no fingers — and I keep score for athletes. What am I?",
        "options": ["A scoreboard", "A clock", "A judge", "A trophy"],
        "answer": "A clock",
        "hint": "Track and field events depend on me.",
        "explanation": "A stopwatch/clock has a face and hands, and times every race.",
    },
    {
        "level": 6,
        "type": "trivia",
        "category": "sports",
        "question": "In tennis, how many Grand Slam tournaments are played each year?",
        "options": ["3", "4", "5", "6"],
        "answer": "4",
        "hint": "Australia, France, Wimbledon, US.",
        "explanation": "The four Grand Slams are Australian Open, French Open, Wimbledon and US Open.",
    },
]


PATTERN_PUZZLES = [
    {
        "level": 1,
        "type": "pattern",
        "category": "logic",
        "question": "Memorize the sequence then repeat it: Red, Blue, Yellow, Green",
        "sequence": ["red", "blue", "yellow", "green"],
        "hint": "Try to remember the order.",
        "explanation": "Pattern recognition trains your working memory.",
    },
    {
        "level": 2,
        "type": "pattern",
        "category": "music",
        "question": "Memorize this melody sequence",
        "sequence": ["do", "mi", "sol", "do", "fa"],
        "hint": "Sing it in your head.",
        "explanation": "Musical sequences strengthen tonal memory.",
    },
    {
        "level": 3,
        "type": "pattern",
        "category": "logic",
        "question": "Remember this ancient symbol sequence",
        "sequence": ["red", "yellow", "blue", "green", "red", "yellow"],
        "hint": "Look for repeating patterns.",
        "explanation": "Recognizing repetition is key to pattern solving.",
    },
    {
        "level": 4,
        "type": "pattern",
        "category": "science",
        "question": "Memorize the lab element colors",
        "sequence": ["blue", "green", "red", "yellow", "blue", "green", "red"],
        "hint": "It's a 4-color cycle.",
        "explanation": "Recurring sequences appear throughout chemistry.",
    },
    {
        "level": 5,
        "type": "pattern",
        "category": "logic",
        "question": "The final sequence — memorize carefully!",
        "sequence": ["red", "blue", "green", "yellow", "red", "green", "blue", "yellow"],
        "hint": "Stay focused.",
        "explanation": "Long sequences test your memory limits.",
    },
]
