import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Brain, Sparkles, RefreshCcw, Check, X } from "lucide-react";
import GameNav from "@/components/GameNav";
import ShopDrawer from "@/components/ShopDrawer";
import TactileButton from "@/components/TactileButton";
import TriviaPuzzle from "@/components/TriviaPuzzle";
import CharacterCompanion from "@/components/CharacterCompanion";
import { getCharacterLine } from "@/data/storyData";
import { generateAiRiddle, submitAnswer, getPlayer, updateProgress } from "@/lib/api";
import {
  getPlayerId,
  getDifficulty,
  getCharacter,
  setCharacter as saveCharacter,
} from "@/lib/gameStore";
import { useEffect } from "react";

const CATEGORIES = [
  { id: "logic", label: "Logic", color: "#38BDF8" },
  { id: "math", label: "Math", color: "#4ADE80" },
  { id: "music", label: "Music", color: "#FB923C" },
  { id: "history", label: "History", color: "#A78BFA" },
  { id: "science", label: "Science", color: "#F472B6" },
  { id: "geography", label: "Geography", color: "#FBBF24" },
];

export default function EndlessMode() {
  const navigate = useNavigate();
  const [category, setCategory] = useState("logic");
  const [puzzle, setPuzzle] = useState(null);
  const [feedback, setFeedback] = useState(null);
  const [streak, setStreak] = useState(0);
  const [loading, setLoading] = useState(false);
  const [shopOpen, setShopOpen] = useState(false);
  const [player, setPlayer] = useState(null);
  const [characterId, setCharacterId] = useState(getCharacter());
  const [companionMood, setCompanionMood] = useState("idle");
  const [companionSpeech, setCompanionSpeech] = useState("");
  const difficulty = getDifficulty();

  useEffect(() => {
    getPlayer(getPlayerId()).then(setPlayer).catch(() => {});
  }, []);

  const newRiddle = async () => {
    setLoading(true);
    setFeedback(null);
    setPuzzle(null);
    try {
      const p = await generateAiRiddle({ category, difficulty });
      setPuzzle(p);
    } catch (e) {
      toast.error("AI failed to generate a riddle", {
        description: "Try again in a moment.",
      });
    } finally {
      setLoading(false);
    }
  };

  const submit = async (val) => {
    if (!puzzle) return;
    try {
      const r = await submitAnswer({
        puzzle_id: puzzle.id,
        selected: val,
        difficulty,
      });
      setFeedback(r);
      if (r.correct) {
        setStreak((s) => s + 1);
        setCompanionMood("happy");
        setCompanionSpeech(getCharacterLine(characterId, "onCorrect"));
        toast.success(`Correct! +${r.coins_earned} coins`);
        const upd = await updateProgress({
          player_id: getPlayerId(),
          level: 0,
          coins: r.coins_earned,
        });
        setPlayer(upd);
      } else {
        setStreak(0);
        setCompanionMood("sad");
        setCompanionSpeech(getCharacterLine(characterId, "onWrong"));
        toast.error("Wrong answer", { description: `Answer: ${r.correct_answer}` });
      }
    } catch {
      toast.error("Could not submit answer.");
    }
  };

  return (
    <div
      className="min-h-screen bg-amber-100"
      style={{
        backgroundImage:
          "radial-gradient(circle at 20% 20%, rgba(167,139,250,0.35), transparent 50%), radial-gradient(circle at 80% 80%, rgba(56,189,248,0.35), transparent 50%)",
      }}
      data-testid="endless-page"
    >
      <GameNav player={player} onOpenShop={() => setShopOpen(true)} />

      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-8">
        <div className="text-center">
          <span className="font-accent text-violet-700">AI-POWERED</span>
          <h1 className="font-display font-bold text-4xl sm:text-5xl text-slate-900 text-shadow-pop">
            Endless Brain Mode
          </h1>
          <p className="mt-2 text-slate-700 font-semibold">
            Infinite riddles, freshly generated by Claude. Pick a category and stretch your mind.
          </p>
          <p
            className="mt-1 text-sm font-bold text-violet-700"
            data-testid="streak-counter"
          >
            🔥 Streak: {streak}
          </p>
        </div>

        <div
          className="mt-6 tactile-card bg-white p-4 flex flex-wrap items-center justify-center gap-2"
          data-testid="category-picker"
        >
          {CATEGORIES.map((c) => (
            <button
              key={c.id}
              onClick={() => setCategory(c.id)}
              className={`tactile-btn px-4 py-2 text-sm ${
                category === c.id ? "" : "opacity-70"
              }`}
              style={{
                backgroundColor: category === c.id ? c.color : "#FFFFFF",
                color: category === c.id ? "#FFFFFF" : "#1E293B",
              }}
              data-testid={`category-${c.id}`}
            >
              {c.label}
            </button>
          ))}
        </div>

        <div className="mt-6 tactile-card bg-white p-6 sm:p-7 min-h-[260px]">
          {!puzzle && !loading && (
            <div className="text-center py-10">
              <Brain
                className="w-16 h-16 mx-auto text-violet-500 animate-float-soft"
                strokeWidth={3}
              />
              <p className="font-display text-xl mt-3 text-slate-800">
                Ready to challenge your brain?
              </p>
              <TactileButton
                color="#A78BFA"
                size="lg"
                icon={Sparkles}
                onClick={newRiddle}
                className="mt-4"
                data-testid="generate-riddle-button"
              >
                Generate Riddle
              </TactileButton>
            </div>
          )}

          {loading && (
            <div className="text-center py-10" data-testid="ai-loading">
              <Sparkles
                className="w-12 h-12 mx-auto text-violet-500 animate-spin"
                strokeWidth={3}
              />
              <p className="font-display text-lg mt-3 text-slate-700">
                Claude is brewing a fresh puzzle…
              </p>
            </div>
          )}

          {puzzle && !loading && (
            <div className="space-y-5">
              <h2
                className="font-display font-bold text-xl sm:text-2xl text-slate-900"
                data-testid="ai-puzzle-question"
              >
                {puzzle.question}
              </h2>
              <TriviaPuzzle puzzle={puzzle} onSubmit={submit} locked={!!feedback} />

              {feedback && (
                <div
                  className={`rounded-2xl border-4 p-4 ${
                    feedback.correct
                      ? "bg-emerald-100 border-emerald-700"
                      : "bg-rose-100 border-rose-700"
                  }`}
                  data-testid={feedback.correct ? "ai-feedback-correct" : "ai-feedback-wrong"}
                >
                  <div className="flex items-center gap-2 font-display font-bold text-lg">
                    {feedback.correct ? (
                      <>
                        <Check
                          className="w-5 h-5 text-emerald-700"
                          strokeWidth={3}
                        />
                        <span className="text-emerald-900">Correct!</span>
                      </>
                    ) : (
                      <>
                        <X className="w-5 h-5 text-rose-700" strokeWidth={3} />
                        <span className="text-rose-900">
                          Answer: {feedback.correct_answer}
                        </span>
                      </>
                    )}
                  </div>
                  <p className="mt-1 text-sm text-slate-800">
                    {feedback.explanation}
                  </p>
                </div>
              )}

              <div className="flex flex-wrap gap-3 justify-end">
                <TactileButton
                  color="#FFFFFF"
                  textColor="#1E293B"
                  size="md"
                  onClick={() => navigate("/")}
                  data-testid="endless-back-button"
                >
                  Back
                </TactileButton>
                <TactileButton
                  color="#A78BFA"
                  size="md"
                  icon={RefreshCcw}
                  onClick={newRiddle}
                  data-testid="another-riddle-button"
                >
                  Another One
                </TactileButton>
              </div>
            </div>
          )}
        </div>
      </main>

      <ShopDrawer
        open={shopOpen}
        onOpenChange={setShopOpen}
        onPlayerUpdate={setPlayer}
      />

      <CharacterCompanion
        characterId={characterId}
        mood={companionMood}
        speech={companionSpeech}
        levelId={0}
        onSwitch={(id) => {
          setCharacterId(id);
          saveCharacter(id);
          setCompanionMood("idle");
          setCompanionSpeech(getCharacterLine(id, "onLevelStart"));
          toast(`Switched to ${id.charAt(0).toUpperCase() + id.slice(1)}!`);
        }}
      />
    </div>
  );
}
